[package]
name = "bevy-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
rocket = "0.4.2"
rocket_contrib = "0.4.11"
rocket_cors = "0.5.1"
serde = "1.0.204"
serde_json = "1.0.120"
